### PR TITLE
Update release tools

### PR DESCRIPTION
**Pull request by kvaps**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

This PR is needed to test the functionality introduced in https://github.com/kubernetes-csi/csi-release-tools/pull/121

    Squashed 'release-tools/' changes from c6a88c6e..ece0f500
    
    ece0f500 check namespace for snapshot-controller
    3b6d17b1 Merge pull request #118 from pohly/cloud-build-timeout
    9318c6cc cloud build: double the timeout, now 1 hour
    86ff5802 Merge pull request #116 from andyzhangx/export-image-name
    c3a96625 allow export image name and registry name
    
    git-subtree-dir: release-tools
    git-subtree-split: ece0f500ed9ee6c197ffce6d410d12edd8bf7365

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by pohly — CHANGES_REQUESTED** [review]
Please re-do the `git subtree pull` with the `--squash` option.

I know, we (someone?) needs to update the README.md...

**Comment by pohly** [comment]
There are no changes left?

I think this was supposed to be a test PR for https://github.com/kubernetes-csi/csi-release-tools/pull/121, right?

That means you have to point `git subtree` at a repo and commit which includes the non-upstream csi-release-tools changes.

**Comment by kvaps** [comment]
Yeah, sorry, I was just bit confused by amount of repos 😅 and forget to do subtree pull in this one

**Comment by xing-yang** [comment]
Please copy the commit message from "https://github.com/kubernetes-csi/csi-driver-host-path/pull/235/commits/5961195ee20007157b4c755d6dbc127f9255ca64" to the PR description for the record.

**Comment by xing-yang** [comment]
/hold

This is a test PR.  Adding hold to avoid it from being merged.

**Comment by pohly** [comment]
Looks good to me.

**Comment by pohly** [comment]
> /hold
> 
> This is a test PR. Adding hold to avoid it from being merged.

We used to have a unit test which prevents merging if it detects new commits, but squashing circumvents that check.

I guess our rule should be:
- squash if you intend to get the PR merged and the squashed commit is really from upstream csi-release-tools
- don't squash when testing additional commits before merging into csi-release-tools

Oh, and a PR description which makes the intention clear :wink:

**Review by pohly — APPROVED** [review]
/lgtm
/approve

**Comment by pohly** [comment]
It's okay to merge this because it squashed the exact same commit that I just approved for csi-release-tools.

**Comment by pohly** [comment]
Fix for failing tests is here: https://github.com/kubernetes/test-infra/pull/20596

**Pull request merged**
