### PR TITLE
Remove snapshot e2e testing from alpha versions.

### PR DESCRIPTION
**Pull request by msau42**
**What type of PR is this?**
//kind failing-test

**What this PR does / why we need it**:
Disables snapshot e2es for 1.16 deployment.

prow.sh uses the e2e version that matches the k8s version. Skew testing
(driver version != k8s version) doesn't work for alpha features.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by msau42** [comment]
Failing testgrid: https://k8s-testgrid.appspot.com/sig-storage-csi-ci#1.16-on-1.17

**Comment by xing-yang** [comment]
Should we also remove "snapshotter" folder and "hostpath/csi-hostpath-snapshotter.yaml" under kubernetes-1.15 and kubernetes-1.16?

**Comment by msau42** [comment]
> Should we also remove "snapshotter" folder and "hostpath/csi-hostpath-snapshotter.yaml" under kubernetes-1.15 and kubernetes-1.16?

I think people may still want to deploy hostpath driver on older versions. We just can't test it in our e2es

**Pull request merged**
