### PR TITLE
Created 1.22 deployment specs; removed 1.18 deployment specs

### PR DESCRIPTION
**Pull request by verult**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

Add deployment spec for 1.22. No spec changes from 1.21 AFAICT.

Remove 1.18 deployment specs since it's no longer in CI or presubmit.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

/assign @pohly 
/cc @jsafrane @mauriciopoppe @msau42 @xing-yang

### CODE REVIEW

**Comment by pohly** [comment]
I just merged https://github.com/kubernetes/test-infra/pull/23462. Let's test with that, just to be sure, before merging.

/hold

**Comment by verult** [comment]
Presubmits looking good.

/hold cancel

**Pull request merged**
