### PR TITLE
WIP: tag large version for master builds

### PR DESCRIPTION
**Pull request by msau42**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
kind [checks kubernetes tagged versions](https://github.com/kubernetes-sigs/kind/blob/9205bac4a8377fb7d301a8c14650592b85a34f58/pkg/cluster/internal/kubeadm/config.go#L451-L459) to figure out which config to use. For master builds, tag a large version so that kind will look for the latest config versions.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by msau42** [comment]
Once https://github.com/kubernetes/test-infra/pull/13434 merges, we can test
```
pull-kubernetes-csi-csi-driver-host-path-alpha-1-15-on-kubernetes-1-15
pull-kubernetes-csi-csi-driver-host-path-alpha-1-15-on-kubernetes-master
```

**Comment by pohly** [comment]
PR #76 has the same change with a clean import from csi-release-tools.

**Pull request closed without merging**
