### PR TITLE
Upgrade sidecars to latest release

### PR DESCRIPTION
**Pull request by RaunakShah**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

This PR upgrades the sidecar containers to their latest releases. 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Upgrade sidecars to latest release
```

### CODE REVIEW

**Review by pohly — CHANGES_REQUESTED** [review]
Did you run `hack/bump-image-versions.sh`?

If I run it, I get additional updates that are not in your PR:

```diff
diff --git a/deploy/kubernetes-1.21-test/hostpath/csi-hostpath-attacher.yaml b/deploy/kubernetes-1.21-test/hostpath/csi-hostpath-attacher.yaml
index 63d11f7f..c8d22cdb 100644
--- a/deploy/kubernetes-1.21-test/hostpath/csi-hostpath-attacher.yaml
+++ b/deploy/kubernetes-1.21-test/hostpath/csi-hostpath-attacher.yaml
@@ -37,7 +37,7 @@ spec:
       serviceAccountName: csi-attacher
       containers:
         - name: csi-attacher
-          image: registry.k8s.io/sig-storage/csi-attacher:v3.4.0
+          image: registry.k8s.io/sig-storage/csi-attacher:v3.5.0
           args:
             - --v=5
             - --csi-address=/csi/csi.sock
diff --git a/deploy/kubernetes-1.21-test/hostpath/csi-hostpath-plugin.yaml b/deploy/kubernetes-1.21-test/hostpath/csi-hostpath-plugin.yaml
index b60d0c6a..181913d2 100644
--- a/deploy/kubernetes-1.21-test/hostpath/csi-hostpath-plugin.yaml
+++ b/deploy/kubernetes-1.21-test/hostpath/csi-hostpath-plugin.yaml
@@ -77,13 +77,13 @@ spec:
           volumeMounts:
           - mountPath: /csi
             name: socket-dir
-          image: registry.k8s.io/sig-storage/livenessprobe:v2.6.0
+          image: registry.k8s.io/sig-storage/livenessprobe:v2.7.0
           args:
           - --csi-address=/csi/csi.sock
           - --health-port=9898
 
         - name: csi-external-health-monitor-controller
-          image: registry.k8s.io/sig-storage/csi-external-health-monitor-controller:v0.4.0
+          image: registry.k8s.io/sig-storage/csi-external-health-monitor-controller:v0.5.0
           args:
             - "--v=5"
             - "--csi-address=$(ADDRESS)"
@@ -97,7 +97,7 @@ spec:
               mountPath: /csi
 
         - name: node-driver-registrar
-          image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.5.0
+          image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.5.1
           args:
             - --v=5
             - --csi-address=/csi/csi.sock
diff --git a/deploy/kubernetes-1.21-test/hostpath/csi-hostpath-provisioner.yaml b/deploy/kubernetes-1.21-test/hostpath/csi-hostpath-provisioner.yaml
index 95e46703..c6dc2be3 100644
--- a/deploy/kubernetes-1.21-test/hostpath/csi-hostpath-provisioner.yaml
+++ b/deploy/kubernetes-1.21-test/hostpath/csi-hostpath-provisioner.yaml
@@ -37,7 +37,7 @@ spec:
       serviceAccountName: csi-provisioner
       containers:
         - name: csi-provisioner
-          image: registry.k8s.io/sig-storage/csi-provisioner:v3.1.0
+          image: registry.k8s.io/sig-storage/csi-provisioner:v3.2.0
           args:
             - -v=5
             - --csi-address=/csi/csi.sock
diff --git a/deploy/kubernetes-1.21-test/hostpath/csi-hostpath-resizer.yaml b/deploy/kubernetes-1.21-test/hostpath/csi-hostpath-resizer.yaml
index 981fead1..5d91e1dc 100644
--- a/deploy/kubernetes-1.21-test/hostpath/csi-hostpath-resizer.yaml
+++ b/deploy/kubernetes-1.21-test/hostpath/csi-hostpath-resizer.yaml
@@ -37,7 +37,7 @@ spec:
       serviceAccountName: csi-resizer
       containers:
         - name: csi-resizer
-          image: registry.k8s.io/sig-storage/csi-resizer:v1.4.0
+          image: registry.k8s.io/sig-storage/csi-resizer:v1.5.0
           args:
             - -v=5
             - -csi-address=/csi/csi.sock
diff --git a/deploy/kubernetes-1.21-test/hostpath/csi-hostpath-snapshotter.yaml b/deploy/kubernetes-1.21-test/hostpath/csi-hostpath-snapshotter.yaml
index 8da6893a..9a45607b 100644
--- a/deploy/kubernetes-1.21-test/hostpath/csi-hostpath-snapshotter.yaml
+++ b/deploy/kubernetes-1.21-test/hostpath/csi-hostpath-snapshotter.yaml
@@ -37,7 +37,7 @@ spec:
       serviceAccountName: csi-snapshotter
       containers:
         - name: csi-snapshotter
-          image: registry.k8s.io/sig-storage/csi-snapshotter:v5.0.1
+          image: registry.k8s.io/sig-storage/csi-snapshotter:v6.0.1
           args:
             - -v=5
             - --csi-address=/csi/csi.sock
diff --git a/deploy/kubernetes-distributed/hostpath/csi-hostpath-plugin.yaml b/deploy/kubernetes-distributed/hostpath/csi-hostpath-plugin.yaml
index 2a717621..8bdf8639 100644
--- a/deploy/kubernetes-distributed/hostpath/csi-hostpath-plugin.yaml
+++ b/deploy/kubernetes-distributed/hostpath/csi-hostpath-plugin.yaml
@@ -25,7 +25,7 @@ spec:
       serviceAccountName: csi-provisioner
       containers:
         - name: csi-provisioner
-          image: registry.k8s.io/sig-storage/csi-provisioner:v3.1.0
+          image: registry.k8s.io/sig-storage/csi-provisioner:v3.2.0
           args:
             - -v=5
             - --csi-address=/csi/csi.sock
@@ -60,7 +60,7 @@ spec:
               name: socket-dir
 
         - name: node-driver-registrar
-          image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.5.0
+          image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.5.1
           args:
             - --v=5
             - --csi-address=/csi/csi.sock
@@ -132,7 +132,7 @@ spec:
           volumeMounts:
           - mountPath: /csi
             name: socket-dir
-          image: registry.k8s.io/sig-storage/livenessprobe:v2.6.0
+          image: registry.k8s.io/sig-storage/livenessprobe:v2.7.0
           args:
           - --csi-address=/csi/csi.sock
           - --health-port=9898
```

**Comment by RaunakShah** [comment]
@pohly thank you, fixed it!

**Review by pohly — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
