### PR TITLE
fixed broken links of testgrid dashboard

### PR DESCRIPTION
**Pull request by siddhikhapare**
**What type of PR is this?**
 /kind documentation

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/test-infra/issues/30370

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by ggriffiths — APPROVED** [review]
Thanks for fixing this! 

/lgtm

**Comment by ggriffiths** [comment]
/assign @pohly 

for approver review.

**Comment by siddhikhapare** [comment]
@ggriffiths When executing the command "make test," I encountered the following error:  
error

**Review by pohly — COMMENTED** [review]
Don't make this change here. Instead fix `csi-release-tools`.

**Comment by siddhikhapare** [comment]
> Don't make this change here. Instead fix `csi-release-tools`.

@pohly @ggriffiths I have done changes here: https://github.com/kubernetes-csi/csi-release-tools/pull/234  Thank you.

**Pull request closed without merging**
