### PR TITLE
WIP: get kind fix for Kubernetes master image building

### PR DESCRIPTION
**Pull request by msau42**
**What type of PR is this?**
/kind failing-test

**What this PR does / why we need it**:
kind image building on Kubernetes master is broken. Need to get fix from kind master. 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by msau42** [comment]
Hm doesn't look like we support building kind in the prow job

**Comment by pohly** [comment]
> Hm doesn't look like we support building kind in the prow job

There's code for it here: https://github.com/kubernetes-csi/csi-driver-host-path/blob/00c769227e52fa8dc0f1460ec6949493c56c13f1/release-tools/prow.sh#L381-L384

But it looks like the kind source code no longer vendors dependencies:
```
commit f721a0cf8c3da6fd85dcb16bbdcf5504cd0277d4
Author: Benjamin Elder <bentheelder@google.com>
Date:   Tue May 7 21:04:11 2019 -0700

    remove vendor/
```

Therefore a plain `go build` no longer works. This should work instead now:
```
git_checkout https://github.com/kubernetes-sigs/kind "$CSI_PROW_WORK/kind" "${CSI_PROW_KIND_VERSION}" --depth=1 &&
(cd "$CSI_PROW_WORK/kind" && run_with_go "${CSI_PROW_GO_VERSION_KIND}" go build -o "${CSI_PROW_WORK}/bin/kind" .)
```

This assumes that we only want to build a newer kind revision. If we want to be more flexible, use this:
```
git_checkout https://github.com/kubernetes-sigs/kind "$GOPATH/src/sigs.k8s.io/kind" "${CSI_PROW_KIND_VERSION}" --depth=1 &&
if [ -d "$GOPATH/src/sigs.k8s.io/kind/vendor" ]; then
   run_with_go "${CSI_PROW_GO_VERSION_KIND}" go build -o "${CSI_PROW_WORK}/bin/kind" sigs.k8s.io/kind; else
  (cd "$GOPATH/src/sigs.k8s.io/kind" && run_with_go "${CSI_PROW_GO_VERSION_KIND}" env GO111MODULE=on);
fi
```

I think I prefer the later.

**Comment by msau42** [comment]
Thanks for the suggestion, trying it out

**Comment by pohly** [comment]
@msau42 if you need help with this, then please let me know.

**Comment by msau42** [comment]
/close

release-tools synced in https://github.com/kubernetes-csi/csi-driver-host-path/pull/84

**Pull request closed without merging**
