### PR TITLE
Create changelog v1.15.0

### PR DESCRIPTION
**Pull request by dfajmon**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Create changelog v1.15.0

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by carlory** [comment]
/hold

need to update the provisioner image once v6.0.0 is cut

**Comment by xing-yang** [comment]
Provisioner v5.1.0 is released.

**Comment by carlory** [comment]
Once https://github.com/kubernetes-csi/csi-driver-host-path/pull/557 is merged, you need to re-generate the release note.

**Comment by carlory** [comment]
cc @dfajmon https://github.com/kubernetes-csi/csi-driver-host-path/pull/557 was merged

**Comment by dfajmon** [comment]
@carlory updated

**Pull request merged**
