### PR TITLE
Fix minor typos

### PR DESCRIPTION
**Pull request by rollandf**

### CODE REVIEW

**Comment by rollandf** [comment]
Signed CLA

**Comment by okartau** [comment]
can we also (to save creation of separate PR) add in this PR fix of remaining two typos that I was able to spot:
under ## Deployment:
```
-The easiest way to test the Hostpath driver is to run `deploy/deploy-hostpath.sh` scrip as show:
+The easiest way to test the Hostpath driver is to run `deploy/deploy-hostpath.sh` script as shown:
```

**Comment by rollandf** [comment]
> can we also (to save creation of separate PR) add in this PR fix of remaining two typos that I was able to spot:
> under ## Deployment:
> 
> ```
> -The easiest way to test the Hostpath driver is to run `deploy/deploy-hostpath.sh` scrip as show:
> +The easiest way to test the Hostpath driver is to run `deploy/deploy-hostpath.sh` script as shown:
> ```

Done

**Comment by okartau** [comment]
once I started piggy-backing my ideas onto another PR...
Some shell prompts in command examples are $ and some are $>, seems a copy-paste leftover artifact. 
I propose to unify all to be $, 
'>', with it's meaning in shell, is not friendly character in examples.

**Comment by rollandf** [comment]
> once I started piggy-backing my ideas onto another PR...
> Some shell prompts in command examples are $ and some are $>, seems a copy-paste leftover artifact.
> I propose to unify all to be $,
> '>', with it's meaning in shell, is not friendly character in examples.

Done

**Comment by okartau** [comment]
Based on proposal by @pohly, I included all fixes from here in #31, which is about big changes in README and would require rebase of this PR here anyway.

**Pull request closed without merging**
