### PR TITLE
Fixed block volume snapshots

### PR DESCRIPTION
**Pull request by jsafrane**
`tar xvfz <snapshot> -C <dst>` does not work for block volumes, because `<dst>` is not a directory but a block file.

Reworked to use `tar` only for filesystem snapshots and simple `cp`/`dd` for block snapshots. As consequence, snapshot suffix is now ".snap" instead of ".tgz".

/kind bug
**Which issue(s) this PR fixes**:

Helps with #88726

**Does this PR introduce a user-facing change?**:

```release-note
Fixed snapshots of block volumes.
```

### CODE REVIEW

**Comment by jsafrane** [comment]
@msau42 @xing-yang @pohly, PTAL

**Comment by msau42** [comment]
Do we support upgrading/restarting the hostpath driver and it being able to restore from previous snapshots? If so we should update the release note to say it's a breaking change

**Comment by jsafrane** [comment]
Not yet, but see #161

**Pull request merged**
