### PR TITLE
update release-tools 

### PR DESCRIPTION
**Pull request by humblec**
> /kind cleanup

-->
```release-note
NONE
```

### CODE REVIEW

**Comment by pohly** [comment]
Are release-tools updates now done manually in each repo on an as-needed basis?

I had a script which did it for several repos at once and also produced better PR descriptions.

**Comment by humblec** [comment]
> Are release-tools updates now done manually in each repo on an as-needed basis?
> 

Came to this after fixing the code-spell error like  in #255.

> I had a script which did it for several repos at once and also produced better PR descriptions.

Actually speaking this PR is half baked with that same script.  That is commits were prepared by the same, however PR was not raised by it. I can try to use the same for entire process too.

**Comment by pohly** [comment]
I've not used that script in a while and we never had an "official" version of it. I was just wondering.

/approve
/lgtm

**Pull request merged**
