### PR TITLE
fix missing published target paths when republish the ephemeral volume

### PR DESCRIPTION
**Pull request by carlory**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

calling `createVolume` twice will reset volume state. It will cause `NodeUnpublishVolume` to be unable to perform unmount operation.

FYI:

- https://github.com/carlory/csi-driver-host-path/blob/4ffa1fc0586fa41cad7ce5861c1e5a98227d8bad/pkg/hostpath/hostpath.go#L223
- https://github.com/carlory/csi-driver-host-path/blob/4ffa1fc0586fa41cad7ce5861c1e5a98227d8bad/pkg/hostpath/nodeserver.go#L230

**Which issue(s) this PR fixes**:

Ref https://github.com/kubernetes/kubernetes/issues/120080

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Fix missing published target paths when republish the ephemeral volume
```

### CODE REVIEW

**Comment by carlory** [comment]
@xing-yang 

the solution to [this issue](https://github.com/kubernetes/kubernetes/issues/120080) depends on the release version which contains the pr. I want to confirm if we need check-pick it into the previous release and cut a patched release, or wait for the next release which contains VAC feature implementation. I'd pefer to the frist option. what do you think?

**Comment by xing-yang** [comment]
Go ahead and cherry-pick it.

**Pull request merged**
