### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by c3y1huang**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
Typo.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jsafrane** [comment]
Can you please merge both your PRs that fix a typo? It does not make sense to have separate PRs for two words.

**Comment by c3y1huang** [comment]
> Can you please merge both your PRs that fix a typo? It does not make sense to have separate PRs for two words.

:+1: done.

**Comment by jsafrane** [comment]
/lgtm
/approve

Thanks for squashing all your fixes in one PR!

**Comment by c3y1huang** [comment]
> /lgtm
> /approve
> 
> Thanks for squashing all your fixes in one PR!

Sorry I've just added more fix for typos. Please take another look. Thank!

**Pull request merged**
