### PR TITLE
DNM: testing PR #399 with csi-tests + GroupController support

### PR DESCRIPTION
**Pull request by nixpanic**
**What type of PR is this?**

/kind failing-test
/hold

**What this PR does / why we need it**:

Testing PR #399 with kubernetes-csi/csi-test#467. This PR only adds a reference to the repository and branch that is used to add GroupController support to the csi-test.

**Which issue(s) this PR fixes**:

This PR will be closed when #399 is merged.

**Special notes for your reviewer**:

Please review the other related PRs instead :handshake: 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nixpanic** [comment]
/test all

Now using csi-test:master, after kubernetes-csi/csi-test#467 was merged.

**Review by ggriffiths — CHANGES_REQUESTED** [review]
Commenting to remove from my queue. Feel free to request if help is needed!

**Comment by nixpanic** [comment]
With the new release of csi-tests, there is no need to run the tests with the master branch anymore.

**Pull request closed without merging**
