### PR TITLE
Cherry pick of #499: replace socat image with hostpathplugin image and bump image versions

### PR DESCRIPTION
**Pull request by carlory**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Ref https://github.com/kubernetes/kubernetes/pull/122489

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
replace socat image with hostpathplugin image and bump image versions
```

### CODE REVIEW

**Comment by xing-yang** [comment]
Why does the cherry-pick goes into the master branch?

**Comment by carlory** [comment]
Oh, it's my mistaken.

**Comment by carlory** [comment]
@xing-yang fixed.

**Comment by xing-yang** [comment]
Waiting for jobs to pass.

**Pull request merged**
