### PR TITLE
Update deploy folders

### PR DESCRIPTION
**Pull request by xing-yang**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by xing-yang** [comment]
/run pull-kubernetes-csi-csi-driver-host-path-1-23-on-kubernetes-master

**Comment by xing-yang** [comment]
/run pull-kubernetes-csi-csi-driver-host-path-1-24-on-kubernetes-master

**Review by pohly — APPROVED** [review]
/lgtm

**Pull request merged**
