### PR TITLE
Bump hostpath image v1.14.1 in deploy

### PR DESCRIPTION
**Pull request by AndrewSirenko**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug

/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

Bump hostpath image to v1.14.1 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

/hold

Until #546 merged and release has been promoted.

**Does this PR introduce a user-facing change?**:

```release-note
Bump hostpath image to v1.14.1 in /deploy
```

### CODE REVIEW

**Comment by AndrewSirenko** [comment]
/hold

Until https://github.com/kubernetes-csi/csi-driver-host-path/pull/546 merged and release has been promoted.

**Comment by AndrewSirenko** [comment]
/unhold

We will merge this before release is cut according to @carlory [here](https://kubernetes.slack.com/archives/C09QZFCE5/p1722351090594339?thread_ts=1721964792.373199&cid=C09QZFCE5)

**Comment by AndrewSirenko** [comment]
Proof

```
❯ rg v1.14.0

...Changelogs...

❯ rg v1.15.0
deploy/kubernetes-1.27/hostpath/csi-hostpath-testing.yaml
69:          image: registry.k8s.io/sig-storage/hostpathplugin:v1.15.0

deploy/kubernetes-distributed/hostpath/csi-hostpath-testing.yaml
67:          image: registry.k8s.io/sig-storage/hostpathplugin:v1.15.0

deploy/kubernetes-distributed/hostpath/csi-hostpath-plugin.yaml
88:          image: registry.k8s.io/sig-storage/hostpathplugin:v1.15.0

deploy/kubernetes-1.27-test/hostpath/csi-hostpath-testing.yaml
67:          image: registry.k8s.io/sig-storage/hostpathplugin:v1.15.0

deploy/kubernetes-1.27-test/hostpath/csi-hostpath-plugin.yaml
34:          image: registry.k8s.io/sig-storage/hostpathplugin:v1.15.0

deploy/kubernetes-1.27/hostpath/csi-hostpath-plugin.yaml
222:          image: registry.k8s.io/sig-storage/hostpathplugin:v1.15.0
```

**Comment by carlory** [comment]
/lgtm
/assign @xing-yang 

for approval

**Comment by AndrewSirenko** [comment]
/hold 

Need to edit to be v1.14.1

**Pull request merged**
