### PR TITLE
Cherry pick of #480: fix missing published target paths when republish the ephemeral volume

### PR DESCRIPTION
**Pull request by carlory**
**What type of PR is this?**

> /kind bug

**What this PR does / why we need it**:

Cherry pick of #480 on release-1.12.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Fix missing published target paths when republish the ephemeral volume
```

### CODE REVIEW

**Comment by xing-yang** [comment]
In the release note, can you add "Cherry-pick PR 480"?

/lgtm
/approve

**Comment by carlory** [comment]
> In the release note, can you add "Cherry-pick PR 480"?

added.

**Pull request merged**
