### PR TITLE
Fix state file update after stage/publish action

### LINKED ISSUE #457: State file not updated after stage/publish action
According to the code logic, when the `NodeStageVolume` and `NodePublishVolume` RPC are called, the volume related state file (`state.json`) should update instantly.

But after test with the latest code, the state file (`state.json`) was not updated after stage/publish action.

cat state.json
```
{"Volumes":[{"VolName":"CSIVolumeName","VolID":"dfd219cb-644c-11ee-91c1-525400def842","VolSize":1048576,"VolPath":"/csi-data-dir/dfd219cb-644c-11ee-91c1-525400def842","VolAccessType":1,"ParentVolID":"","ParentSnapID":"","Ephemeral":false,"NodeID":"","Kind":"","ReadOnlyAttach":false,"Attached":false,"Staged":null,"Published":null}],"Snapshots":null}
```

### PR DESCRIPTION
**Pull request by astraw99**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Fixed the `state.UpdateVolume` function, to update the state file correctly.

**Which issue(s) this PR fixes**:
Fixes #457

**Special notes for your reviewer**:
Tested with the latest code, safe to merge.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by pohly** [comment]
Change looks good, but neither the PR nor the issue explains what the user-visible effect of this bug was. Can you elaborate?

**Comment by pohly** [comment]
In other words, why does this PR matter?

**Comment by astraw99** [comment]
> Change looks good, but neither the PR nor the issue explains what the user-visible effect of this bug was. Can you elaborate?

Currently the state file `state.json` was not updated after stage or publish action, there are two issues:
1. When the `hostpathplugin` binary restart, the old data in the memory was lost, lead to subsequent RPC calls fail.
2. When there is no restart, user go to the `/csi-data-dir` to check the `state.json`, will not see the latest content.

For example, before `NodeStageVolume`: (see the field `"Staged":null`)
```
{"Volumes":[{"VolName":"CSIVolumeName","VolID":"dfd219cb-644c-11ee-91c1-525400def842","VolSize":1048576,"VolPath":"/csi-data-dir/dfd219cb-644c-11ee-91c1-525400def842","VolAccessType":1,"ParentVolID":"","ParentSnapID":"","Ephemeral":false,"NodeID":"","Kind":"","ReadOnlyAttach":false,"Attached":false,"Staged":null,"Published":null}],"Snapshots":null}
```
After `NodeStageVolume`: (see the field `"Staged":["/mnt/hostpath"]`)
```
{"Volumes":[{"VolName":"CSIVolumeName","VolID":"dfd219cb-644c-11ee-91c1-525400def842","VolSize":1048576,"VolPath":"/csi-data-dir/dfd219cb-644c-11ee-91c1-525400def842","VolAccessType":1,"ParentVolID":"","ParentSnapID":"","Ephemeral":false,"NodeID":"","Kind":"","ReadOnlyAttach":false,"Attached":false,"Staged":["/mnt/hostpath"],"Published":null}],"Snapshots":null}
```

**Comment by pohly** [comment]
Are you using this driver in production?

**Comment by astraw99** [comment]
> Are you using this driver in production?

Not in production, just used to test CSI RPCs.

**Review by pohly — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
