### PR TITLE
initial prow job

### PR DESCRIPTION
**Pull request by pohly**
This implements the kubernetes-csi release process described in https://github.com/kubernetes/enhancements/pull/807.

### CODE REVIEW

**Comment by pohly** [comment]
/test pull-sig-storage-csi-driver-host-path

Point to remember: all kubernetes-csi repos must be listed in prow/plugins.yaml before commands work, see https://github.com/kubernetes/test-infra/pull/11537.

**Comment by BenTheElder** [comment]
```console
+ cd /home/prow/go/src/k8s.io/kubernetes
+ ginkgo -p -v ./test/e2e -- -ginkgo.focus=External.Storage.*csi-hostpath -ginkgo.skip=\[Feature:|\[Disruptive\] -storage.testdriver=/home/prow/go/pkg/csiprow.kor3UsM3eJ/hostpath-test-driver.yaml
./.prow.sh: 244: ./.prow.sh: ginkgo: not found
```
the kind part works fine now, the script needs some fixing :+1:

**Comment by pohly** [comment]
First job where E2E tests ran: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-csi_csi-driver-host-path/16/pull-sig-storage-csi-driver-host-path/14

There's one E2E failure (`External Storage [Driver: csi-hostpath] [Testpattern: Dynamic PV (block volmode)] volumeMode [It] should fail in binding dynamic provisioned PV to PVC`). I need to check whether that is something that the hostpath driver is supposed to  pass.

**Comment by BenTheElder** [comment]
FYI currently junit output from ginkgo is not being picked up, if you make sure it is written to  somewhere in $ARTIFACTS Prow will render the structured results and let you view the failure output specifically.

**Comment by pohly** [comment]
Benjamin Elder <notifications@github.com> writes:
> FYI currently junit output from ginkgo is not being picked up, if you
> make sure it is written to  somewhere in $ARTIFACTS Prow will render
> the structured results and let you view the failure output
> specifically.

I know, that's one of the TODOs.

Ginkgo is going to be easy. More interesting will be to also generate
JUnit output for the individual tests done by "make test". I'm currently
leaning towards leaving "make test" as-is and just parsing the output.

**Comment by pohly** [comment]
The test failure was caused by https://github.com/kubernetes-csi/csi-driver-host-path/issues/21

**Comment by BenTheElder** [comment]
I would recommend getting the ginkgo output FWIW, it should be pretty easy and make it quicker to diagnose failures from those tests. It just needs to be placed in $ARTIFACTS for upload.

/test pull-sig-storage-csi-driver-host-path

**Comment by pohly** [comment]
@BenTheElder `make test` doesn't run Ginkgo tests, just various checks like gofmt.

/test pull-sig-storage-csi-driver-host-path

**Comment by pohly** [comment]
@msau42 if the tests succeed, then please merge. This is up-to-date with https://github.com/kubernetes-csi/csi-release-tools/pull/9 (= d87eccb).

**Comment by msau42** [comment]
Can you explain what these jobs are doing:
pull-sig-storage-csi-driver-host-path-kubernetes-1-13 
pull-sig-storage-csi-driver-host-path-kubernetes-master

Can we also separate out the non-K8s tests, alpha e2es and non-alpha e2es?

**Comment by pohly** [comment]
> Can you explain what these jobs are doing:
> pull-sig-storage-csi-driver-host-path-kubernetes-1-13
> pull-sig-storage-csi-driver-host-path-kubernetes-master

Those are from previous revisions of test-infra and obsolete. The current set of tests are the ones from https://github.com/kubernetes-csi/csi-driver-host-path/pull/16#issuecomment-480057783

> Can we also separate out the non-K8s tests, alpha e2es and non-alpha e2es?

Yes, but that will be done in test-infra without requiring changes in the individual components.

**Comment by pohly** [comment]
> > Can we also separate out the non-K8s tests, alpha e2es and non-alpha e2es?
>
>Yes, but that will be done in test-infra without requiring changes in the individual components.

See https://github.com/kubernetes/test-infra/pull/12088

While testing I noticed that sig-release-tools needs some enhancement and one fix to make this actually work (the check for which tests to run is slightly broken). I have the fixed, but would like to get this PR merged first, to unblock testing of the periodic jobs. Right now they aren't passing because they are based on csi-driver-host-path master, which doesn't have Prow support yet.

**Comment by pohly** [comment]
@msau42 you or someone else (@jsafrane?) also needs to approve.

**Pull request merged**
